wifi_ssid: "SSID"
wifi_password: "PASSWORD"

mqtt_broker: MQTT_IP_ADDR
mqtt_port: 1883
mqtt_username: ""
mqtt_password: ""

ota_password: "PASSWORD"
api_password: "PASSWORD"

tibber_api_token: "TIBBER_TOKEN"

## for v1
hm2500_1_mac: "E8:8D:A6:00:00:01"
hm2500_2_mac: "E8:8D:A6:00:00:02"

## for v2
hm2500_3_mac: "E8:8D:A6:00:00:03"
hm2500_4_mac: "E8:8D:A6:00:00:04"

mqtt_grid_power: "tibber-esp/sensor/power/state"
mqtt_opendtu_limit_state: "openDTU/XXXXXXXXXXXX/state/limit_relative"
mqtt_opendtu_limit_cmd: "openDTU/XXXXXXXXXXXX/cmd/limit_persistent_relative"

