wifi_ssid: "SSID"
wifi_password: "PASSWORD"

mqtt_broker: MQTT_IP_ADDR

ota_password: "PASSWORD"
api_password: "PASSWORD"

tibber_api_token: "TIBBER_TOKEN"

hm2500_1_mac: "E8:8D:A6:XX:XX:XX"
hm2500_2_mac: "E8:8D:A6:XX:XX:XX"

