alias: B2500 - Received Data
description: ""
trigger:
  - platform: mqtt
    topic: hame_energy/+/device/+/ctrl
condition: []
action:
  - service: python_script.b2500_parse_respond
    data:
      message: "{{ trigger.payload }}"
      topic: " {{ trigger.topic }}"
mode: single
