alias: B2500 - Received Data
description: ""
trigger:
  - platform: mqtt
    topic: hame_energy/<DEVICE_TYPE/device/<DEVICE_MAC>/ctrl
condition: []
action:
  - service: python_script.b2500_parse_respond
    data:
      message: "{{ trigger.payload }}"
mode: single

