alias: B2500 - Received Data
description: ""
trigger:
  - platform: mqtt
    topic: hame_energy/HMB-4/device/e88da6af01e1/ctrl
condition: []
action:
  - service: python_script.b2500_parse_respond
    data:
      message: "{{ trigger.payload }}"
mode: single

