alias: B2500 - Request Data
description: ""
trigger:
  - platform: time_pattern
    seconds: /5
condition: []
action:
  - service: mqtt.publish
    data:
      qos: "0"
      topic: hame_energy/<DEVICE_TYPE>/App/<DEVICE_MAC>/ctrl
      payload: cd=01
mode: single

